server:
  port: 8080


#æ•°æ®åº“é…ç½®
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_medical?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  #redisé…ç½®
  data:
    redis:
      host: localhost
      port: 6379


# mybatis-plus é…ç½®
mybatis-plus:
  # 1. å‘Šè¯‰ MP å»å“ªé‡Œæ‰¾ XML æ–‡ä»¶
  mapper-locations: classpath:mapper/*.xml

  # 2. åŸç”Ÿé…ç½®é¡¹ (æ—¥å¿—ã€é©¼å³°ç­‰)
  configuration:
    # å¼€å¯ SQL æ—¥å¿—æ‰“å°
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # å¼€å¯é©¼å³°å‘½åæ˜ å°„ (æ•°æ®åº“ user_name -> Java userName)
    map-underscore-to-camel-case: true

  # 3. ã€å…³é”®ï¼ã€‘å…¨å±€ç­–ç•¥é…ç½® (è¿™æ˜¯è§£å†³æŠ¥é”™çš„æ ¸å¿ƒ)
  global-config:
    db-config:
      # ğŸš« å½»åº•ç¦ç”¨ DDL åŠŸèƒ½ï¼Œé˜²æ­¢å¯åŠ¨æ—¶æŠ¥ Runner ç±»å‹é”™è¯¯
      ddl-enabled: false
      # å¦‚æœä½ çš„è¡¨åå’Œå®ä½“åä¸ä¸€è‡´ï¼Œå¯ä»¥åœ¨è¿™é‡Œè®¾ç½®å‰ç¼€ï¼Œæ¯”å¦‚è¡¨æ˜¯ tb_userï¼Œå®ä½“æ˜¯ User
      # table-prefix: tb_


minio:
  endpoint: http://localhost:9000  # æ³¨æ„æ˜¯ 9000ï¼Œä¸æ˜¯ 9001
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: yicheng-medical

